version: "3"
services:
  app:
    build: .
    container_name: ci_test_app
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    # volumesやdepends_onも必要に応じて追加
