name: Deploy to Docker Compose (IPv6)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection (IPv6)
        run: |
          ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -6 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IPV6 }} "echo 'SSH connection successful'"

      - name: Copy files to server
        run: |
          rsync -avz --exclude='.git*' ./ ${{ secrets.SSH_USER }}@[${{ secrets.SSH_HOST_IPV6 }}]:${{ secrets.SSH_PATH }}

      - name: Deploy with Docker Compose
        run: |
          ssh -6 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_IPV6 }} "cd ${{ secrets.SSH_PATH }} && docker-compose pull && docker-compose up -d"
